name: Manage Labeling Tasks

on:
  workflow_dispatch:
    inputs:
      video_name:
        description: 'Video Name (e.g., DJI_20230925154521_0008_D_(30s))'
        required: true
      batch_number:
        description: 'Batch Number'
        required: true

jobs:
  create_labeling_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE="Labeling Task: ${{ github.event.inputs.video_name }} Batch ${{ github.event.inputs.batch_number }}"
          ISSUE_BODY="Please label the images in ${{ github.event.inputs.video_name }}/batch_${{ github.event.inputs.batch_number }}/frames"
          ISSUE_NUMBER=$(gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --label "labeling" | grep -oP '#\K\d+')
          echo "Created issue #$ISSUE_NUMBER"

      - name: Create branch and PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BATCH_INFO="${{ github.event.inputs.video_name }} Batch ${{ github.event.inputs.batch_number }}"
          BRANCH_NAME="labeling-task-${BATCH_INFO// /-}"

          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b $BRANCH_NAME

          echo "Labeling task for $BATCH_INFO" > labeling_task.md
          git add labeling_task.md
          git commit -m "Initialize labeling task for $BATCH_INFO"
          git push -u origin $BRANCH_NAME

          PR_URL=$(gh pr create --title "Labeling Task: $BATCH_INFO" --body "This PR is for the labeling task: $BATCH_INFO. Please label the images in this batch and commit your changes to this branch." --base main --head $BRANCH_NAME)

          gh issue comment $ISSUE_NUMBER --body "A new branch and pull request have been created for this labeling task. You can find the pull request here: $PR_URL"